project:
  type: website
  output-dir: docs

website:
  title: "Fear is the Vibe Killer"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Past Events"
        href: past.qmd
format:
  html:
    theme: vapor
    title-block-categories: false
