---
title: "Where to Dance in KW"
date-modified: today
language:
  title-block-modified: "Last Updated"
---
## Thursday May 28, 2026

### 👉 Sunset Shenanigans

Location: Waterloo Park @ [Westmount Entrance, near soccer fields](https://www.google.com/maps/place/Waterloo+Park+Soccer+Field+%231/@43.4651924,-80.5394727,461m/data=!3m1!1e3!4m6!3m5!1s0x882bf51e4941b757:0x9a0d526d5fc29cbb!8m2!3d43.4654126!4d-80.5387027!16s%2Fg%2F11f62g0qth?entry=ttu&g_ep=EgoyMDI2MDUyMC4wIKXMDSoASAFQAw%3D%3D)

#### 6pm-sunset

* [DJ Zoe](https://www.instagram.com/tasselhazard/)

[Info](https://www.instagram.com/p/DY0fioSDRzu/)


## Saturday May 30, 2026

### 👉 BDay Jam Dance Night 

Location: [42 Erb St. E](https://maps.app.goo.gl/V4Q2NsGXNVoXRK9i9)

#### 10pm-Late

* [Shaux Radio](https://www.instagram.com/shauxradio/) - Deep House
* [Danasonic](https://www.instagram.com/danasonic_/) - Lush Dance

[Info](https://www.instagram.com/p/DYVjPuCgeaw/)


### 👉 Purple Room Reunion

Location: Revive Karaoke Bar @ [28 King St N, Waterloo](https://maps.app.goo.gl/5r3mSMYBSawvvNGh9)

#### 9pm-2:30am

* [Matt Lok](https://www.instagram.com/mattlok.dj/)
* [DJ Jace](https://www.instagram.com/dj_jace_jrfit/)
* [Sylent Syd](https://www.instagram.com/sylentsyd/)
* [Jermz](https://www.instagram.com/jermz0800/)

[Info](https://www.instagram.com/p/DX7UUtWR3k0/)


## Tuesday June 2, 2026

### 👉 Under The Bridge

Location: DM [@underthebridge_dance](https://www.instagram.com/underthebridge_dance/) for details

#### 7pm-11pm

* [DJ Divaa](https://www.instagram.com/existentialcowgirl/)
* [DJ Delfine](https://www.instagram.com/djdelfine/)
* [Kasia](https://www.instagram.com/koshkasia/)
* [Rish.AF](https://www.instagram.com/rish.af_/)
* [DJ Ronnie V](https://www.instagram.com/dj_ronnie_v/)

[Info](https://www.instagram.com/p/DYGg6k_jGqc/)


## Saturday June 6, 2026

### 👉 Pride in Paradise: The Crystal Room

Location: The Museum @ [10 King St W.](https://maps.app.goo.gl/NyLhFMoBFudPfztp8)

#### 8:30pm-late

* [Delicious DJ](https://www.instagram.com/deliciousdj_/)
* [DJ Divaa](https://www.instagram.com/existentialcowgirl/)
* [DJ UBU](https://www.instagram.com/diegg/)

[Info](https://www.instagram.com/p/DYNDRTgFgz1/)


### 👉 Round & Round

Location: Button Factory Arts Centre @ [25 Regina St S.](https://maps.app.goo.gl/PL8h6rpDSYMdQPLw6)

#### 8pm-1am

* [Danasonic](https://www.instagram.com/danasonic_/)
* [R449](https://www.instagram.com/r4iv9_/)
* [DJ Zizek](https://www.instagram.com/corykobbert/)
* [Hallucinex](https://www.instagram.com/debaserhead/)

[Tickets](https://luma.com/vwdiah4u)


## Saturday June 13, 2026

### 👉 After Dark HUGE TENT PARTY

Location: Hungarian Canadian Club @ [979 Kossuth Rd Cambridge](https://maps.app.goo.gl/EX7hcHjhsqnFBD3p7)

#### 10pm-4am

* [Kelly Mazur](https://www.instagram.com/kellymazur_/)
* [DJ Aleksandra](https://www.instagram.com/djaleksandra/)
* [DJ Jace](https://www.instagram.com/dj_jace_jrfit/)
* [Ochie](https://www.instagram.com/andres_ochie/)
* [Mark Saunders](https://www.instagram.com/marksaundersmusic_official/)

[Info](https://www.instagram.com/p/DYx2DrstpW3/)

NOTE: cash only at door & bar, no ATM on site!


---

> Know of a dance party that we should share? [DM us](https://www.instagram.com/fearisthevibekiller/) or [email us](mailto:getdown@fearisthevibekiller.com).

