---
title: "Past Events"
date-modified: today
language:
  title-block-modified: "Last Updated"
---
## Saturday January 31, 2026

<!-- event-meta: post_url=https://www.instagram.com/p/DThd4pcjQ-9/; ticket_link=https://www.instagram.com/p/DThd4pcjQ-9/; event_date=2026-01-31; event_name=after dark -->

### 👉 after dark

Location: <Hungarian Canadian Club> @ [979 Kossuth Rd Cambridge](https://maps.app.goo.gl/EX7hcHjhsqnFBD3p7)

#### 9pm-2am

* [mark saunders](https://on.soundcloud.com/uvZQFxEsZX9NnWEH8)
* gabor ankuza (b.m.e.)
* dj g-love-
* [dj jace](http://linktr.ee/DJ_Jace_FGA)
* [dj uwe](https://www.instagram.com/dj.uwe_fernengel/)

[Info](https://www.instagram.com/p/DThd4pcjQ-9/)


## Friday January 30, 2026

### 👉 Leo Full Moon

Location: Conrad Centre for the Performing Arts @ [36 King St W, Kitchener, ON N2G 1A3](https://maps.app.goo.gl/ZvH5ZUeYtRQP5aT2A)

#### 7pm-12am

* [Cacaoboy](https://www.instagram.com/p/DTTgROTj5ku/)
* [Auraboros](https://www.instagram.com/auraboros_beats/)
* [Kasia](https://www.instagram.com/koshkasia/)

[Tickets](https://www.eventbrite.ca/e/leo-full-moon-ecstatic-dance-party-cacao-ceremony-tickets-1979505687799)


<!-- event-meta: post_url=https://www.instagram.com/p/DTikUR9j6ar/; ticket_link=https://www.instagram.com/p/DTikUR9j6ar/; event_date=2026-01-30; event_name=Leo Full Moon - Ecstatic Dance Party & Cacao Ceremony -->
### 👉 Leo Full Moon - Ecstatic Dance Party & Cacao Ceremony

Location: <LOCATION NAME> @ [LOCATION ADDRESS](GOOGLE MAPS LINK)

#### 7:00pm-11:59pm

* [Kasha](https://linktr.ee/kashalikekesha)

[Info](https://www.instagram.com/p/DTikUR9j6ar/)


## Thursday January 29, 2026

<!-- event-meta: post_url=https://www.instagram.com/p/DTpHLxpjoZg; ticket_link=https://www.instagram.com/p/DTpHLxpjoZg; event_date=2026-01-29; event_name=Open Decks KW -->
### 👉 Open Decks KW

Location: Pin Up Arcade Bar @ [247 King St N, Unit 8](https://maps.app.goo.gl/Ni62muiQV4K25JZRA)

#### 9pm-1pm

* [cultranaut](https://linktr.ee/cultranaut)
* You???

[Info](https://www.instagram.com/p/DTpHLxpjoZg)


## Saturday January 24, 2026

### 👉 DJ Night At Counterpoint Brewing

Location: Counterpoint Brewing @ [1601 Victoria St. N](https://maps.app.goo.gl/3ZMNXn9oNmiFH6uU8)

#### 5pm-9pm

* [Uwe](https://www.instagram.com/dj.uwe_fernengel/)
* [DJ Jace](https://www.instagram.com/dj_jace_jrfit/)

[Info](https://www.instagram.com/p/DTI1jhTjsNs/)


## Friday January 23, 2026

<!-- event-meta: post_url=https://www.instagram.com/p/DTsLt0vkdeg; ticket_link=https://www.instagram.com/p/DTsLt0vkdeg; event_date=2026-01-23; event_name=Sylent Syd's Pop Shop -->
### 👉 Sylent Syd's Pop Shop

Location: <LOCATION NAME> @ [LOCATION ADDRESS](GOOGLE MAPS LINK)

#### 8:00pm-11:00pm

* [Sylent Syd](https://www.mixcloud.com/sylentsyd/the-one-armed-octopus-aka-pus/)
* [grandsurflounge](https://www.grandtrunksaloon.com/the-surf)

[Info](https://www.instagram.com/p/DTsLt0vkdeg)


## Saturday January 17, 2026

<!-- event-meta: post_url=https://www.instagram.com/p/DTbaIlDAGtN/; ticket_link=https://www.instagram.com/p/DTbaIlDAGtN/; event_date=2026-01-17; event_name=Yeti -->

### 👉 Nice People Dancing To Good Music

Location: The Yeti @ [14 Eby St N, Kitchener](https://maps.app.goo.gl/beeXFx8uwKqUmAif9)

#### 9pm-late

* [DJ Jace](http://linktr.ee/DJ_Jace_FGA)
* [Amanda Elemental](https://on.soundcloud.com/KLUq3m8Q5S0YTlInRE)
* [Kasia](https://on.soundcloud.com/rzWuG7Ev6275rXecqt)

[Info](https://www.instagram.com/p/DTbaIlDAGtN/)



## Saturday December 6, 2025

### 👉 AWAKEN Kitchener - A night of breath, dance, music, and connection.

Location: Conrad Center for the Performing Arts @ [36 King St. West, Kitchener, ON](https://maps.app.goo.gl/uV4bVvRr5NHyxHU27)

#### 6:30pm-12:30am

* [Corey Sheikh](https://www.instagram.com/corey.sheikh/)

[Tickets](https://app.brightstarevents.com/event/881ecc30-cd4c-4e73-a2f6-5272e8380801)


### 👉 [One Big Gay Disco](https://www.instagram.com/onebiggaydisco/): LOVE IS THE MESSAGE

Location: The Hub @ [125 King St. W, Kitchener](https://maps.app.goo.gl/Ak4bVgJ6FKT3zQtF6)

#### 9pm-2:30am

* [Skinny Dip](https://www.instagram.com/toricarney/)
* [Aquarius](https://www.instagram.com/aquariusgroovin/)
* [DIVAA](https://www.instagram.com/existentialcowgirl/)
* [Danasonic](https://www.instagram.com/danasonic_/)

[Tickets](https://www.eventbrite.ca/e/love-is-the-message-tickets-1974948787989)


## Sunday October 26, 2025

### 👉 Solar Symbiosis

Location: [50 Borden Ave South, Kitchener](https://maps.app.goo.gl/9S2KrJ34h6BoikTz6)

#### 3pm-10pm

* [DJ DIVAA](https://www.instagram.com/existentialcowgirl)
* [DANA SONIC](https://www.instagram.com/danasonic_)
* [Magnatech](https://www.instagram.com/magnatechmusic/)
* [Raevn](https://www.instagram.com/raeriddims/)

[Tickets](https://www.eventbrite.ca/e/solar-symbiosis-tickets-1783202509709)


## Wednesday October 15, 2025

### 👉 Under The Bridge

Location: DM [@underthebridge_dance](https://www.instagram.com/underthebridge_dance/) for location

#### 6pm-9pm

* [Jess Tunes](https://www.instagram.com/jess__tunes/)
* [DJ Delfine](https://www.instagram.com/djdelfine/)
* Maybe you? (see link below for details)

[Info](https://www.instagram.com/p/DPnP_XHjO9e/)


## Saturday October 4, 2025

### 👉 Haunted House of Divaa

Location: Jane Bond @ [5 Princess St W, Waterloo, ON](https://www.google.com/maps/place/5+Princess+St+W,+Waterloo,+ON)

#### 10pm-1am

* [DIVAA](https://www.instagram.com/existentialcowgirl)
* [Aquarius](https://www.instagram.com/aquariusgroovin/)

[Info](https://www.instagram.com/p/DPKqBfmDQOi/)


## Friday September 26, 2025

### 👉 Uptown Rinse 011

Location: Heuther Hotel @ [59 King St N. Waterloo](https://maps.app.goo.gl/rognH8PucZHefvSc9)

#### 9pm-1am

* [Risky Medicine](https://linktr.ee/mr.blu)
* [DJ Denim](https://www.instagram.com/cammatthewmusicandart/)

[Tickets](https://www.eventbrite.ca/e/uptown-rinse-011-tickets-1677080937229)


## Sunday September 21, 2025

### 👉 Under The Bridge

Location: DM [@underthebridge_dance](https://www.instagram.com/underthebridge_dance/) for location

#### 7pm-10:30pm

* [Anzor](https://www.instagram.com/classic.anzor/)
* [Danasonic](https://www.instagram.com/danasonic_)
* [DJ Denim](https://www.instagram.com/cammatthewmusicandart/)
* [Alternate Reality](https://soundcloud.com/dj-alternatereality)
* [DJ Jess](https://www.instagram.com/jess__tunes/)
* [Cultranaut](https://www.instagram.com/cultranaut/)
* [DJ Skinnydip](https://www.instagram.com/toricarney)
* [Kasia](https://www.instagram.com/koshkasia/)

[Info](https://www.instagram.com/p/DOgbMQgDsY9/)


## Saturday September 20, 2025

### 👉 sPARK!

Location: East Gazeebo, Waterloo Park @ [50 Young St W, Waterloo](https://maps.app.goo.gl/tWmLpimiCXC4w15H7)

#### 5pm-11pm

* [Kasia](https://www.instagram.com/koshkasia/)
* Kor
* Mos
* DJ Soft
* Jonah K

[Info](https://www.instagram.com/p/DOt7WVZEsol-ZM3AOjJOv644DOGTsNJtTpyzxk0/)


## Friday September 12, 2025

### 👉 One Big Gay Disco

Location: The Hub @ [125 King St. W, Kitchener](https://maps.app.goo.gl/Ak4bVgJ6FKT3zQtF6)

#### 9pm-2am

* [Delicious](https://www.instagram.com/deliciousdj_/)
* [Existential Cowgirl](https://www.instagram.com/existentialcowgirl/)
* [Slamboxxx](https://www.instagram.com/i.am.slamoiselle/)
* [Danasonic](https://www.instagram.com/danasonic_/)

[Tickets](https://www.eventbrite.ca/e/wonderland-tickets-1612866630509)


## Thursday August 28, 2025

### 👉 Uptown Rinse 010

Location: secret location - DM organizers for details

#### 6pm-11pm

* [DJ Denim](https://www.instagram.com/cammatthewmusicandart/)
* CDarth
* [DJ Jace](https://www.instagram.com/dj_jace_jrfit/)
* Suhaana
* [Amanda Elemental](https://www.instagram.com/amanda.elemental/)

[Info](https://www.instagram.com/p/DNWf_hjgE-r/)


## Saturday August 9, 2025

### 👉 Funk Pop-A-Roll

Location: Jane Bond @ [5 Princess St W, Waterloo, ON](https://www.google.com/maps/place/5+Princess+St+W,+Waterloo,+ON)

#### 10pm-close

* [SylentSyd](https://www.instagram.com/sylentsyd/)

[Info](https://www.instagram.com/p/DNAkc7rR-fo/)


## Tuesday August 5, 2025

### 👉 Under The Bridge

Location: DM [@underthebridge_dance](https://www.instagram.com/underthebridge_dance/) for location

#### 6pm-10:30pm

* [Jess Tunes](https://www.instagram.com/jess__tunes/)
* [Jonny Rocha](https://www.instagram.com/dj.jonnyrocha/)
* [Arsh](https://www.instagram.com/arsherman21/)
* [Uncle Doobie](https://www.instagram.com/uncledoobie/)
* [Jacobilly](https://www.instagram.com/itsjacobilly/)
* [Robin Green](https://www.instagram.com/robingreen1702/)

[Info](https://www.instagram.com/p/DMIruj2uXqi/)


## Friday August 1, 2025

### 👉 Midpoint Rave

Location: Huether Hotel – Rooftop Patio @ [59 King St N, Waterloo, ON](https://maps.google.com/?q=59+King+St+N,+Waterloo,+ON)

#### 10pm–Late

* [JACOBILLY](https://www.instagram.com/itsjacobilly)
* [DJ Delfine](https://www.instagram.com/djdelfine/)

[Tickets](https://www.eventbrite.com/e/midpoint-rave-tickets-1462405968619)


## Saturday July 26, 2025

### 👉 Rekindling

Location: [300 Mill St.](https://maps.app.goo.gl/uo27y5ye9zbNnj5z5)

#### 4pm-11pm

[Info](https://www.instagram.com/p/DKziwoOMKuW/)


### 👉 Shrek Rave: Cool Is Dead!

Location: The Hub @ [125 King St. W, Kitchener](https://maps.app.goo.gl/Ak4bVgJ6FKT3zQtF6)

#### 10pm-close

[Tickets](https://www.ticketweb.ca/event/shrek-rave-the-hub-tickets/13785004)


## Friday July 25, 2025

### 👉 Pop Shop

Location: Grand Surf @ [87 Ontario St S, Kitchener, ON N2G 1X5](https://maps.app.goo.gl/i2hPHfznvMhmvGUH6)

#### 7pm-11pm

* [Sylent Syd](https://www.instagram.com/sylentsyd/)

[Info](https://www.instagram.com/p/DMfKn3NRdEB/)


### 👉 Underground House Experience

Location: Rade's Restaurant @ [301 King St E. Unit 106 & 107](https://maps.app.goo.gl/c4wr3xikv3b3CJoa6)

#### 8pm-1am

* Theodore
* Juicmane
* DJ KRN x DJ HRY
* 250HMS
* CDArth

[Info](https://www.instagram.com/p/DMeWqpAs6VL/)


## Saturday July 19, 2025

### 👉 Magical Mermaid Ball

Location: Upstairs @ [Lancaster Smokehouse](https://maps.app.goo.gl/xmXVsWs8Jy42QAt19)

#### 9pm-Midnight

* Ben Cormier
* [DJ Jace](https://www.instagram.com/dj_jace_jrfit/)

[Info](https://www.instagram.com/p/DL8FygPPJ5b)


## Saturday July 12, 2025

### 👉 Funk Pop-A-Roll

Location: Jane Bond @ [5 Princess Street West, Waterloo, Ontario](https://maps.google.com/?q=5+Princess+Street+West+Waterloo+Ontario)

#### 10PM–CLOSE

* [Sylent Syd](https://www.instagram.com/sylentsyd/)

[Info](https://www.instagram.com/p/DL6NIAeR0_N)


## Thursday July 10, 2025

### 👉 Neon Majlis Presents: Sunset Shenanigans

Location: [Willow River Park](https://maps.app.goo.gl/gGkS7Pfc3V8N6Arw9)

#### 6:30pm-Sunset

* [Amanda Elemental](https://www.instagram.com/amanda.elemental/)

[Info](https://www.instagram.com/p/DL0QHIpJMYn/)


## Saturday July 5, 2025

### 👉 House of DIVAA

Location: The Jane Bond @ [5 Princess St W, Waterloo, ON N2L 2X7](https://maps.google.com/?q=The+Jane+Bond,+5+Princess+St+W,+Waterloo,+ON+N2L+2X7)

#### 10PM–2AM

* [Danasonic](https://www.instagram.com/danasonic_)
* [DIVAA](https://www.instagram.com/existentialcowgirl)

[Info](https://www.instagram.com/p/DLsFDOxA1cd).


## Sunday June 29, 2025

### 👉 Sunset Hvrmony: Canada D-Eh

Location: The Huether Hotel @ [59 King St N, Waterloo, ON](https://www.google.com/maps/place/59+King+St+N,+Waterloo,+ON)

#### 4PM - LATE

* Filip B2B Eric
* Alicia B2B Cait
* Dutch B2B Mea
* SVNBVRNED
* 2Cozy
* Delze B2B Jxzkson

[Info](https://www.instagram.com/p/DLV2A6eJjfJ)


## Friday June 27, 2025

### 👉 House Night

Location: Jane Bond @ [5 Princess St W, Waterloo, ON](https://www.google.com/maps/place/5+Princess+St+W,+Waterloo,+ON)

#### 11PM - LATE

* [Sylent Syd](https://www.mixcloud.com/sylentsyd/the-one-armed-octopus-aka-pus/) – house set

[Info](https://www.instagram.com/p/DLTmq_qRLwa)


### 👉 KW Family Friendly Bike Rave

Location: [Victoria Park Clock Tower](https://maps.app.goo.gl/59XBZdbgnxmEGxZy7)

#### Meet up time 7:30pm

[More info](https://www.instagram.com/p/DK_J47ytOYi/).


### 👉 Pop Shop

Location: Grand Surf Lounge @ [30 Ontario St, Kitchener, ON](https://www.google.com/maps/place/30+Ontario+St,+Kitchener,+ON)

#### 7PM - 11PM

* [Sylent Syd](https://www.mixcloud.com/sylentsyd/the-one-armed-octopus-aka-pus/) – funk, pop, groove selections

[Info](https://www.instagram.com/p/DLTmq_qRLwa)


## Sunday June 22, 2025

### 👉 Beats and Brews

Location: Whoopsie Daisy Drinks @ [1 Victoria St S, Kitchener](https://maps.app.goo.gl/dzsAGMhgu64CxqNd9).

#### 11am-3pm

* [DJ Raevn](https://www.instagram.com/raeriddims/) delivers groovy global sounds

[Tickets](https://www.eventbrite.ca/e/beats-and-brews-tickets-1380712190329)


### 👉 [NeonMajlis](https://www.instagram.com/neonmajlis/) and [EcstaticDanceKW](https://www.instagram.com/ecstaticdancekw/) Present Radiance: Outdoor Solstice Dance Party

Location: [Waterloo Park](https://maps.app.goo.gl/xVkFyiTrF3uD7q1SA)

#### 1pm-Sunset

**DJ Sets by:**

* [Reva Wild](https://www.instagram.com/reva.wild/)
* [DJ Delfine](https://www.instagram.com/djdelfine/)
* [Amanda Elemental](https://www.instagram.com/amanda.elemental/)

[More info](https://www.instagram.com/p/DKzoZWrgqYi/)


## Saturday June 21, 2025

### 👉 [Lost Vessel Vintage](https://lostvessel.com/) 4 Year Anniversary Party

Location: Lost Vessel Vintage @ [6 Princess St. W, Waterloo](https://maps.app.goo.gl/EPmVjmdDUUkZm4aa9)

#### 12pm-7pm

* [DJ Sylent Syd](https://www.instagram.com/sylentsyd/) will be spinning a mix of House, Soul, Funk, New Wave & Punk

[More info](https://www.instagram.com/p/DK2To3mA3Nt/).


### 👉 [One Big Gay Disco](https://www.instagram.com/onebiggaydisco/) Presents Party of Life

Location: The Hub @ [125 King St. W, Kitchener](https://maps.app.goo.gl/Ak4bVgJ6FKT3zQtF6)

#### 9pm-2am

**Featuring:**

* [The Patchouli Brothers](https://www.instagram.com/thepatchoulibrothers/) a dynamic disco duo, truly a match made in heaven
* [TJ Traxx](https://www.instagram.com/tj.traxx/) known for heaving hitting sets, back to bless us with late night house
* [Amanda Elemental](https://www.instagram.com/amanda.elemental/) sets filled with uplifting energy that guide the room into movement
* [DJ Divaa](https://www.instagram.com/existentialcowgirl/) shaking the room with electro disco energy and raw, gritty house beats

[Tickets](https://tinyurl.com/OBGDPARTYOFLIFE).


## Friday June 20, 2025

### 👉 Late Night Groove Entertainment & FGA presents: Summer Solstice!

Location: TBA

#### 8pm-12:30am

**Featuring:**

* [Jesney](https://www.instagram.com/jesneylife/), London - Progressive Techno, FGA, Blu Music, NEC
* [DJ Denim](https://www.instagram.com/cammatthewmusicandart/), KW - House and Techno
* [Uwe](https://www.instagram.com/dj.uwe_fernengel/) b2b [Matt Brennan](https://www.instagram.com/djmattbrennan/), KW - Tribal, Late Night Groove Entertainment
* [DJ Jace](https://www.instagram.com/dj_jace_jrfit/), KW - Deep House / Techno FGA, Like That Underground

Follow DJ Jace and Uwe for more info.


---

That's a _lot_ of getting down!

